import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./css/index.scss";
import AppProvider from "./components/app-provider";
import { CookiesProvider } from "next-client-cookies/server";
import Header from "./components/header/header";
import Body from "./components/body/body";
import Layout from "./components/layout/layout";
import ContextProvider from "./components/context-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextHub",
  description: "Generated by Anh Khoa",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CookiesProvider>
          <ContextProvider>
            <AppProvider>
              <Layout header={<Header />} body={<Body>{children}</Body>} />
            </AppProvider>
          </ContextProvider>
        </CookiesProvider>
      </body>
    </html>
  );
}
